module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: { 'green-tea': '#435c50', 'green-tea-dense': '#2a4236' },
      backgroundImage: {
        accessories: "url('/assets/accessories.jpg')",
        men: "url('/assets/men.jpg')",
        women: "url('/assets/women.jpg')",
        youth: "url('/assets/youth.jpg')",
        'product-1': "url('/assets/product-1.jpg')",
        'product-2': "url('/assets/product-2.jpg')",
        'product-3': "url('/assets/product-3.jpg')",
        'product-4': "url('/assets/product-4.jpg')",
        'product-5': "url('/assets/product-5.jpg')",
        'product-6': "url('/assets/product-6.jpg')",
        'product-7': "url('/assets/product-7.jpg')",
        'product-8': "url('/assets/product-8.jpg')",
        'product-9': "url('/assets/product-9.jpg')",
        'product-10': "url('/assets/product-10.jpg')",
        'product-11': "url('/assets/product-11.jpg')",
        'product-12': "url('/assets/product-12.jpg')",
        'product-13': "url('/assets/product-13.jpg')",
        'product-14': "url('/assets/product-14.jpg')",
        'product-15': "url('/assets/product-15.jpg')",
      },
    },
  },
  plugins: [],
};
